### PR TITLE
IMGW telemetry dataset

### PR DESCRIPTION
**Pull request by bczernecki**
Downloading IMGW-PIB measurements from telemetry system

### CODE REVIEW

**Comment by Nowosad** [comment]
No internet connection:

```

══ Skipped tests (5) ═══════════════════════════════════════════════════════════
• empty test (5): 'test-hydro_metadata_imgw.R:7:1',
  'test-meteo_imgw_daily.R:11:1', 'test-meteo_noaa_co2.R:1:1',
  'test-nearest_stations_noaa.R:1:1', 'test-nearest_stations_ogimet.R:3:1'

══ Warnings ════════════════════════════════════════════════════════════════════
── Warning ('test-meteo_metadata_imgw.R:5:3'): tests to be re-written meteo_metadata_imgw ──
cannot open file '/tmp/RtmpaEp3Fu/working_dir/RtmpqYw3MW/fileeed1343621da': No such file or directory
Backtrace:
    ▆
 1. └─climate:::meteo_metadata_imgw("hourly", "synop") at test-meteo_metadata_imgw.R:5:2
 2.   └─climate:::clean_metadata_meteo(...)
 3.     └─base::readLines(temp, warn = FALSE)
 4.       └─base::file(con, "r")

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-meteo_metadata_imgw.R:5:3'): tests to be re-written meteo_metadata_imgw ──
Error in `file(con, "r")`: cannot open the connection
Backtrace:
    ▆
 1. └─climate:::meteo_metadata_imgw("hourly", "synop") at test-meteo_metadata_imgw.R:5:2
 2.   └─climate:::clean_metadata_meteo(...)
 3.     └─base::readLines(temp, warn = FALSE)
 4.       └─base::file(con, "r")
── Failure ('test-meteo_ogimet.R:44:3'): meteo_ogimet works! ───────────────────
`meteo_ogimet(...)` did not throw an error.
── Failure ('test-meteo_ogimet.R:58:5'): meteo_ogimet works! ───────────────────
nrow(multiyr) > 70 is not TRUE

`actual`:   FALSE
`expected`: TRUE 

[ FAIL 3 | WARN 1 | SKIP 5 | PASS 25 ]
```

**Comment by Nowosad** [comment]
This should be fixed before sending to CRAN.

**Comment by Nowosad** [comment]
Also: there is a typo in DESCRIPTION: "Meterology" (wow)

**Comment by Nowosad** [comment]
This typo is also in README (and maybe a few other places...)

**Comment by bczernecki** [comment]
IMHO it's ready for re-review @Nowosad :)

**Comment by Nowosad** [comment]
@bczernecki, a few comments:

1. `meteo_imgw_telemetry_stations` -> `stations_meteo_imgw_telemetry` (as in `stations_ogimet`)
2. The warning below should be suppressed:

``` r
library(climate)
telemetry_stations = meteo_imgw_telemetry_stations()
#> Warning in FUN(X[[i]], ...): NAs introduced by coercion
```

**Comment by bczernecki** [comment]
> ```r
> telemetry_stations = meteo_imgw_telemetry_stations()
> ```

corrected in the most recent commit

**Review by Nowosad — APPROVED** [review]

**Pull request merged**
