### PR TITLE
climate 1.0.4

### PR DESCRIPTION
**Pull request by bczernecki**
- improved distance calculations
- minor improvements and bug fixes

### CODE REVIEW

**Comment by bczernecki** [comment]
@Nowosad  - there's sth wrong with iconv on Ubuntu machines. Frankly speaking I have no idea what might be the core reason, but maybe you have some extra hints...

**Comment by Nowosad** [comment]
I tried to reproduce Ubuntu issues on a few machines (including Fedora and rhub's Ubuntu) without any success. I would assume this is a spurious error.

**Comment by bczernecki** [comment]
let me play with `.Renviron`... 
BTW, regardless this weird CI staff this is on its to cran :partying_face:

**Comment by bczernecki** [comment]
Adding artificially `.Renviron` but only for Linux solved the problem. Merging to master

**Pull request merged**
